language: ruby
rvm:
  - "1.9"
  - "2.0"
  - "2.1"
  - "2.2"
env:
  - INCLUDE_LINGUIST=true
  - INCLUDE_LINGUIST=false

before_install:
  - if [[ "$INCLUDE_LINGUIST" == "true" ]]; then BUNDLE_GEMFILE=Gemfile.optional; sudo apt-get install libicu-dev -y; fi
